name: CI - Jest & SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run Jest tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ecommerce-pricing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ecommerce-pricing/coverage/

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ecommerce-pricing/coverage/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=eduardo-mtr47_Partiel-clean-code
            -Dsonar.organization=eduardo-mtr47
            -Dsonar.sources=ecommerce-pricing/src
            -Dsonar.tests=ecommerce-pricing/tests
            -Dsonar.javascript.lcov.reportPaths=ecommerce-pricing/coverage/lcov.info
            -Dsonar.exclusions=node_modules/**
